---
name: comments recipe on issues

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]
# idea from : https://pakstech.com/blog/gh-actions-issue-comments/
jobs:
  comments:
    name: get PR SHA
    runs-on: ubuntu-20.04
    if: ${{ contains(github.event.comment.body , '/deploydb')}}
    steps:
    
    - name: Add Comment
      if: ${{ success() }}
      uses: actions/github-script@v4
      with:
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'You have ordered a Database Deploy, You can see this workflow running on: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}',
          });  

    - uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.addLabels({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: ['sqldeploy']
          })    

    - uses: actions/checkout@v2

    - name: Fail randomly
      run: |
        cat README.md
        exit $((RANDOM % 2))   

    - name: Message success
      if: ${{ success() }}
      uses: actions/github-script@v4
      with:
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Deployment succeeded! ✅',
          });          
    - name: Message failure
      if: ${{ failure() }}
      uses: actions/github-script@v4
      with:
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Deployment failed! ❌',
          });          
